version: '3'
services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: crisiscleanup
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
  web:
    build: .
    command: >
      bash -c "
        # Run web server
        # bundle exec unicorn -p 3000 -c ./config/unicorn.rb
        bundle exec rails server -e development -b 0.0.0.0 -p 3000
        "
    ports: ['8080:3000']     
    entrypoint: /app/docker-entrypoint.sh
    env_file: 
      - .env.docker
    environment:
      RAILS_ENV: docker
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    depends_on:
      - postgres
      - redis

volumes:
  postgres: