version: '3'
services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: crisiscleanup
      POSTGRES_PASSWORD: crisiscleanup
    ports:
      - '5432:5432'
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
