version: 2
jobs:
  build:
    parallelism: 2
    docker:
    - image: circleci/ruby:2.4.2-jessie-node
      environment:
        RAILS_ENV: test
    - image: circleci/postgres:9.6.2-alpine
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: crisiscleanup       
    steps:
    - checkout
    
    # Which version of bundler?
    - run:
        name: Which bundler?
        command: bundle -v

    # Restore bundle cache
    - restore_cache:
        keys:
          - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          - rails-demo-bundle-v2-
    
    # Install gem dependencies
    - run:
        name: Bundle Install
        command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
        
    # Store bundle cache
    - save_cache:
        key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

    # Only necessary if app uses webpacker or yarn in some other way
    - restore_cache:
        keys:
          - rails-demo-yarn-{{ checksum "yarn.lock" }}
          - rails-demo-yarn-

    - run:
        name: Yarn Install
        command: yarn install --cache-folder ~/.cache/yarn

    # Store yarn / webpacker cache
    - save_cache:
        key: rails-demo-yarn-{{ checksum "yarn.lock" }}
        paths:
          - ~/.cache/yarn        

    # - run: bundle exec rake assets:precompile

    - run:
        name: Wait for DB
        command: dockerize -wait tcp://localhost:5432 -timeout 1m

    - run:
        command: bundle exec rake db:create db:schema:load --trace
        environment:
          RAILS_ENV: test
          RACK_ENV: test
    # Test
    #   This would typically be a build job when using workflows, possibly combined with build
    # This is based on your 1.0 configuration file or project settings
    - run:
        name: RAILS_ENV=test bundle exec rspec -r rspec_junit_formatter --format RspecJunitFormatter -o $CIRCLE_TEST_REPORTS/rspec/junit.xml
        command: if [ "$CIRCLE_NODE_INDEX" == "0" ]; then RAILS_ENV=test bundle exec rspec -r rspec_junit_formatter --format RspecJunitFormatter -o $CIRCLE_TEST_REPORTS/rspec/junit.xml; fi
    # Teardown
    #   If you break your build into multiple jobs with workflows, you will probably want to do the parts of this that are relevant in each
    # Save test results
    - store_test_results:
        path: /tmp/circleci-test-results
    # Save artifacts
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results
