development: &development
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password: crisiscleanup
  host: localhost
  port: 5432

docker:
  <<: *development
  database: postgres
  host: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: crisiscleanup_test
  pool: 5
  username: postgres
  password: crisiscleanup
  host: <%= ENV['POSTGRES_HOST'] ||= 'localhost' %>
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: crisiscleanup_production
  pool: 5
  username:
  password:
