relative_urls: false
remove_script_host: false
document_base_url: "https://www.crisiscleanup.org/"
toolbar:
  - styleselect | bold italic | undo redo
  - image | link
plugins:
  - code
  - image
  - link
  - table