name: CI

on: [push]

env:
  RAILS_ENV: test

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    # container:
    #   image: circleci/ruby:2.4.4-jessie-node

    
    services:
      postgres:
        image: postgres:9.6.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: crisiscleanup
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@master

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.4.6

    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 8
    
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-

    - name: Install dependencies
      run: |
        gem install bundler -v "< 2.0" 
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Yarn install
      run: yarn install

    - name: ESLint
      run: bin/webpack

    - name: Setup test database
      env:
        RAILS_ENV: test
        RACK_ENV: test
      run: |
        bundle exec rake db:create db:schema:load --trace

    - name: Run tests
      run: |
        bundle exec rspec --format progress \
                          --format RspecJunitFormatter 